#!/bin/bash

set -e

if [ -n "$1" ]; then
    repopath="$1"
else
    repopath="."
fi

hash="$(cat .3bs/Asset/current.ver)"

children="$(git -C "$repopath" rev-list --all --ancestry-path $hash..HEAD)"
significant="$(git -C "$repopath" show-ref --hash)"

update_paths="$(comm -12 \
    <(echo "$children" | sort) \
    <(echo "$significant" | sort)\
)"

annotated_paths="$(echo $update_paths | git name-rev --annotate-stdin)"

format() {
    echo "$1" | sed 's/(/\| /g;s|/[^| ]*/|/|g;s|[^| ]*/||g;s/)//g;s/\n/\n 1) /g'
}

format "$annotated_paths"