#!/bin/sh

set -xe

echo 'Installing 3bs into local directory...'


prohibit_git=false
for arg in "$@"; do
    [ "$arg" = "--prohibit-git" ] && \
        prohibit_git=true && break
done

cd `dirname $0` # Typically .3bs
    git rev-parse HEAD > Asset/current.ver
    \cp Parent/. .. -far
    rm -fr Parent
cd -

rm LICENSE
rm README.md
rm -fr .git

printf "{\n}" > deps.json
mkdir Source

# Create a git repository if git is available.
if command -v git &> /dev/null && [ "$prohibit_git" = false ]
then
    echo "Initializing git repository..."
    git init . --quiet
    git add . --all
    git commit -m "Initial commit." --quiet
    echo "Git repository initialized."
else
    echo "Git not found; skipping git repository initialization."
fi

rm $0 # Remove this install script: typically .3bs/install

echo '3bs installed.'