#!/bin/bash

source .3bs/*essential.sh

here="`readlink -f "`dirname ${BASH_SOURCE[0]}`"`"

_DisplayTrace "Retrieving dependencies..."
_DisplayTrace "Arguments: $@"

rm -fr Dependency/

ConsoleCommands=$(
    cat deps.json | handlerpath=".3bs/Asset" \
        $here/ResolveConsoleCommands
)

bash -c "$ConsoleCommands"

for Dependency in `ls -A Dependency/`
do
    handler="Tool/DependencyHandler/$Dependency"
    test -f $handler && bash $handler Transform
done